### 회원가입 user
POST {{host}}/auth/signup
Content-Type: application/json

{
  "username": "user",
  "password": "1234",
  "roles": ["ROLE_READ"]
}

### 회원가입 admin
POST {{host}}/auth/signup
Content-Type: application/json

{
  "username": "admin",
  "password": "1234",
  "roles": ["ROLE_READ", "ROLE_WRITE"]
}

### 로그인
POST {{host}}/auth/signin
Content-Type: application/json

{
  "username": "user",
  "password": "1234"
}